#pragma line 1 "gemm.c" ::: 0
#pragma line 1 "gemm.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 289 "/opt/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 427 "/opt/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "gemm.c" 2 ::: 194
#pragma line 1 "./gemm.h" 1 ::: 195
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 198
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 226
#pragma line 128 "/usr/include/features.h" 3 4 ::: 327
#pragma line 149 "/usr/include/features.h" 3 4 ::: 341
#pragma line 177 "/usr/include/features.h" 3 4 ::: 343
#pragma line 193 "/usr/include/features.h" 3 4 ::: 346
#pragma line 350 "/usr/include/features.h" 3 4 ::: 377
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 381
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 416
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 422
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 445
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 486
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 492
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 510
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 516
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 520
#pragma line 148 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 522
#pragma line 166 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 526
#pragma line 193 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 536
#pragma line 253 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 589
#pragma line 306 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 630
#pragma line 339 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 651
#pragma line 385 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 675
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 676
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 678
#pragma line 386 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 680
#pragma line 375 "/usr/include/features.h" 2 3 4 ::: 681
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 706
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 717
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 722
#pragma line 399 "/usr/include/features.h" 2 3 4 ::: 723
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 724
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 730
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 771
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 774
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 776
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 804
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 806
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 808
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 869
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 876
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 894
#pragma line 76 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 899
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 910
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 979
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 993
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 996
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 997
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1029
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1045
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1070
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1073
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1078
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1100
#pragma line 897 "/usr/include/wchar.h" 3 4 ::: 1121
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1124
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1135
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1145
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1147
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1151
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1200
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1201
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1207
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1209
#pragma line 177 "/usr/include/libio.h" 3 4 ::: 1233
#pragma line 245 "/usr/include/libio.h" 3 4 ::: 1244
#pragma line 293 "/usr/include/libio.h" 3 4 ::: 1285
#pragma line 302 "/usr/include/libio.h" 3 4 ::: 1287
#pragma line 334 "/usr/include/libio.h" 3 4 ::: 1309
#pragma line 390 "/usr/include/libio.h" 3 4 ::: 1335
#pragma line 434 "/usr/include/libio.h" 3 4 ::: 1339
#pragma line 464 "/usr/include/libio.h" 3 4 ::: 1354
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1366
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1372
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1374
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1384
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1406
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1422
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1439
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1471
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1517
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1531
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1534
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 1610
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1649
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1690
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 1803
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 1866
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 1915
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 1926
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 1956
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 1984
#pragma line 910 "/usr/include/stdio.h" 3 4 ::: 2017
#pragma line 931 "/usr/include/stdio.h" 3 4 ::: 2029
#pragma line 3 "./gemm.h" 2 ::: 2032
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2033
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2066
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2091
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 2094
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 2104
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 2133
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 2151
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 2152
#pragma line 64 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 3 4 ::: 2208
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2209
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 2246
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2248
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 2252
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 2255
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2273
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2274
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2276
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2278
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 2286
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2304
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2307
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2310
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 2312
#pragma line 65 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 2 3 4 ::: 2313
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 2347
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 2353
#pragma line 83 "/usr/include/stdlib.h" 3 4 ::: 2369
#pragma line 96 "/usr/include/stdlib.h" 3 4 ::: 2371
#pragma line 302 "/usr/include/stdlib.h" 3 4 ::: 2493
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 2507
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2528
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2545
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2567
#pragma line 115 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2575
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2584
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2585
#pragma line 58 "/usr/include/time.h" 3 4 ::: 2606
#pragma line 74 "/usr/include/time.h" 3 4 ::: 2609
#pragma line 90 "/usr/include/time.h" 3 4 ::: 2612
#pragma line 102 "/usr/include/time.h" 3 4 ::: 2615
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2618
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2619
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2620
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2645
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2648
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2658
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 2693
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 2724
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2747
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2749
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 2751
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2752
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 2756
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2796
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2807
#pragma line 118 "/usr/include/time.h" 3 4 ::: 2828
#pragma line 44 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2836
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 2838
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2873
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 2918
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2948
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 2952
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 2970
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 2981
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2983
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 3005
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 3009
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3031
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3033
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 3035
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3036
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3059
#pragma line 124 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3079
#pragma line 211 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3149
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3180
#pragma line 315 "/usr/include/stdlib.h" 2 3 4 ::: 3181
#pragma line 465 "/usr/include/stdlib.h" 3 4 ::: 3324
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3353
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3378
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3403
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 3406
#pragma line 493 "/usr/include/stdlib.h" 2 3 4 ::: 3415
#pragma line 514 "/usr/include/stdlib.h" 3 4 ::: 3428
#pragma line 533 "/usr/include/stdlib.h" 3 4 ::: 3435
#pragma line 555 "/usr/include/stdlib.h" 3 4 ::: 3447
#pragma line 575 "/usr/include/stdlib.h" 3 4 ::: 3458
#pragma line 635 "/usr/include/stdlib.h" 3 4 ::: 3505
#pragma line 658 "/usr/include/stdlib.h" 3 4 ::: 3514
#pragma line 713 "/usr/include/stdlib.h" 3 4 ::: 3521
#pragma line 729 "/usr/include/stdlib.h" 3 4 ::: 3527
#pragma line 753 "/usr/include/stdlib.h" 3 4 ::: 3542
#pragma line 912 "/usr/include/stdlib.h" 3 4 ::: 3693
#pragma line 948 "/usr/include/stdlib.h" 3 4 ::: 3695
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 3704
#pragma line 956 "/usr/include/stdlib.h" 2 3 4 ::: 3722
#pragma line 4 "./gemm.h" 2 ::: 3725
#pragma line 1 "./support.h" 1 ::: 3726
#pragma line 1 "/usr/include/inttypes.h" 1 3 4 ::: 3728
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 1 3 4 ::: 3756
#pragma line 1 "/usr/include/stdint.h" 1 3 4 ::: 3790
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wchar.h" 1 3 4 ::: 3817
#pragma line 27 "/usr/include/stdint.h" 2 3 4 ::: 3849
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3850
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3852
#pragma line 28 "/usr/include/stdint.h" 2 3 4 ::: 3854
#pragma line 47 "/usr/include/stdint.h" 3 4 ::: 3861
#pragma line 116 "/usr/include/stdint.h" 3 4 ::: 3923
#pragma line 132 "/usr/include/stdint.h" 3 4 ::: 3931
#pragma line 152 "/usr/include/stdint.h" 3 4 ::: 3936
#pragma line 200 "/usr/include/stdint.h" 3 4 ::: 3976
#pragma line 211 "/usr/include/stdint.h" 3 4 ::: 3978
#pragma line 223 "/usr/include/stdint.h" 3 4 ::: 3980
#pragma line 235 "/usr/include/stdint.h" 3 4 ::: 3982
#pragma line 255 "/usr/include/stdint.h" 3 4 ::: 3995
#pragma line 287 "/usr/include/stdint.h" 3 4 ::: 4019
#pragma line 297 "/usr/include/stdint.h" 3 4 ::: 4021
#pragma line 34 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 2 3 4 ::: 4023
#pragma line 28 "/usr/include/inttypes.h" 2 3 4 ::: 4024
#pragma line 51 "/usr/include/inttypes.h" 3 4 ::: 4032
#pragma line 85 "/usr/include/inttypes.h" 3 4 ::: 4036
#pragma line 101 "/usr/include/inttypes.h" 3 4 ::: 4038
#pragma line 117 "/usr/include/inttypes.h" 3 4 ::: 4040
#pragma line 133 "/usr/include/inttypes.h" 3 4 ::: 4042
#pragma line 150 "/usr/include/inttypes.h" 3 4 ::: 4044
#pragma line 159 "/usr/include/inttypes.h" 3 4 ::: 4046
#pragma line 168 "/usr/include/inttypes.h" 3 4 ::: 4048
#pragma line 186 "/usr/include/inttypes.h" 3 4 ::: 4052
#pragma line 202 "/usr/include/inttypes.h" 3 4 ::: 4054
#pragma line 218 "/usr/include/inttypes.h" 3 4 ::: 4056
#pragma line 234 "/usr/include/inttypes.h" 3 4 ::: 4058
#pragma line 251 "/usr/include/inttypes.h" 3 4 ::: 4060
#pragma line 270 "/usr/include/inttypes.h" 3 4 ::: 4069
#pragma line 289 "/usr/include/inttypes.h" 3 4 ::: 4076
#pragma line 3 "./support.h" 2 ::: 4101
#pragma line 74 "./support.h" ::: 4160
#pragma line 5 "./gemm.h" 2 ::: 4221
#pragma line 2 "gemm.c" 2 ::: 4247
