#pragma line 1 "gemm.c" ::: -10
#pragma line 1 "gemm.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 289 "/opt/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 427 "/opt/Xilinx/Vivado_HLS/2017.1/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "gemm.c" 2 ::: 184
#pragma line 1 "./gemm.h" 1 ::: 185
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 188
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 216
#pragma line 128 "/usr/include/features.h" 3 4 ::: 317
#pragma line 149 "/usr/include/features.h" 3 4 ::: 331
#pragma line 177 "/usr/include/features.h" 3 4 ::: 333
#pragma line 193 "/usr/include/features.h" 3 4 ::: 336
#pragma line 350 "/usr/include/features.h" 3 4 ::: 367
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 371
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 406
#pragma line 353 "/usr/include/features.h" 2 3 4 ::: 412
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 435
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 476
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 482
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 500
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 506
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 510
#pragma line 148 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 512
#pragma line 166 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 516
#pragma line 193 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 526
#pragma line 253 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 579
#pragma line 306 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 620
#pragma line 339 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 641
#pragma line 385 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 665
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 666
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 668
#pragma line 386 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 670
#pragma line 375 "/usr/include/features.h" 2 3 4 ::: 671
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 696
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 707
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 712
#pragma line 399 "/usr/include/features.h" 2 3 4 ::: 713
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 714
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 720
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 761
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 764
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 766
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 794
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 796
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 798
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 859
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 866
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 884
#pragma line 76 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 889
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 900
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 969
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 983
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 986
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 987
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1019
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1035
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1060
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1063
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1068
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1090
#pragma line 897 "/usr/include/wchar.h" 3 4 ::: 1111
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1114
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1125
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1135
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1137
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1141
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1190
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1191
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1197
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1199
#pragma line 177 "/usr/include/libio.h" 3 4 ::: 1223
#pragma line 245 "/usr/include/libio.h" 3 4 ::: 1234
#pragma line 293 "/usr/include/libio.h" 3 4 ::: 1275
#pragma line 302 "/usr/include/libio.h" 3 4 ::: 1277
#pragma line 334 "/usr/include/libio.h" 3 4 ::: 1299
#pragma line 390 "/usr/include/libio.h" 3 4 ::: 1325
#pragma line 434 "/usr/include/libio.h" 3 4 ::: 1329
#pragma line 464 "/usr/include/libio.h" 3 4 ::: 1344
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1356
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1362
#pragma line 102 "/usr/include/stdio.h" 3 4 ::: 1364
#pragma line 119 "/usr/include/stdio.h" 3 4 ::: 1374
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1396
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1412
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1429
#pragma line 208 "/usr/include/stdio.h" 3 4 ::: 1461
#pragma line 268 "/usr/include/stdio.h" 3 4 ::: 1507
#pragma line 305 "/usr/include/stdio.h" 3 4 ::: 1521
#pragma line 318 "/usr/include/stdio.h" 3 4 ::: 1524
#pragma line 411 "/usr/include/stdio.h" 3 4 ::: 1600
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1639
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1680
#pragma line 655 "/usr/include/stdio.h" 3 4 ::: 1793
#pragma line 731 "/usr/include/stdio.h" 3 4 ::: 1856
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 1905
#pragma line 825 "/usr/include/stdio.h" 3 4 ::: 1916
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 1946
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 1974
#pragma line 910 "/usr/include/stdio.h" 3 4 ::: 2007
#pragma line 931 "/usr/include/stdio.h" 3 4 ::: 2019
#pragma line 3 "./gemm.h" 2 ::: 2022
#pragma line 1 "/usr/include/stdlib.h" 1 3 4 ::: 2023
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2056
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2081
#pragma line 33 "/usr/include/stdlib.h" 2 3 4 ::: 2084
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 1 3 4 ::: 2094
#pragma line 39 "/usr/include/x86_64-linux-gnu/bits/waitflags.h" 3 4 ::: 2123
#pragma line 42 "/usr/include/stdlib.h" 2 3 4 ::: 2141
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 1 3 4 ::: 2142
#pragma line 64 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 3 4 ::: 2198
#pragma line 1 "/usr/include/endian.h" 1 3 4 ::: 2199
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/endian.h" 1 3 4 ::: 2236
#pragma line 37 "/usr/include/endian.h" 2 3 4 ::: 2238
#pragma line 59 "/usr/include/endian.h" 3 4 ::: 2242
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 1 3 4 ::: 2245
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2263
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2264
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2266
#pragma line 29 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2268
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/byteswap-16.h" 1 3 4 ::: 2276
#pragma line 36 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 2 3 4 ::: 2294
#pragma line 56 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2297
#pragma line 96 "/usr/include/x86_64-linux-gnu/bits/byteswap.h" 3 4 ::: 2300
#pragma line 61 "/usr/include/endian.h" 2 3 4 ::: 2302
#pragma line 65 "/usr/include/x86_64-linux-gnu/bits/waitstatus.h" 2 3 4 ::: 2303
#pragma line 43 "/usr/include/stdlib.h" 2 3 4 ::: 2337
#pragma line 57 "/usr/include/stdlib.h" 3 4 ::: 2343
#pragma line 83 "/usr/include/stdlib.h" 3 4 ::: 2359
#pragma line 96 "/usr/include/stdlib.h" 3 4 ::: 2361
#pragma line 302 "/usr/include/stdlib.h" 3 4 ::: 2483
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/types.h" 1 3 4 ::: 2497
#pragma line 33 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2518
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2535
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2557
#pragma line 115 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2565
#pragma line 132 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2574
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2575
#pragma line 58 "/usr/include/time.h" 3 4 ::: 2596
#pragma line 74 "/usr/include/time.h" 3 4 ::: 2599
#pragma line 90 "/usr/include/time.h" 3 4 ::: 2602
#pragma line 102 "/usr/include/time.h" 3 4 ::: 2605
#pragma line 133 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2608
#pragma line 146 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2609
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 2610
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 2635
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2638
#pragma line 186 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2648
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/select.h" 1 3 4 ::: 2683
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/select.h" 1 3 4 ::: 2714
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 2737
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 2739
#pragma line 23 "/usr/include/x86_64-linux-gnu/bits/select.h" 2 3 4 ::: 2741
#pragma line 31 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2742
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sigset.h" 1 3 4 ::: 2746
#pragma line 34 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2786
#pragma line 1 "/usr/include/time.h" 1 3 4 ::: 2797
#pragma line 118 "/usr/include/time.h" 3 4 ::: 2818
#pragma line 44 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2826
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/time.h" 1 3 4 ::: 2828
#pragma line 46 "/usr/include/x86_64-linux-gnu/sys/select.h" 2 3 4 ::: 2863
#pragma line 98 "/usr/include/x86_64-linux-gnu/sys/select.h" 3 4 ::: 2908
#pragma line 220 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2938
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 1 3 4 ::: 2942
#pragma line 26 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 2960
#pragma line 60 "/usr/include/x86_64-linux-gnu/sys/sysmacros.h" 3 4 ::: 2971
#pragma line 223 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 2973
#pragma line 268 "/usr/include/x86_64-linux-gnu/sys/types.h" 3 4 ::: 2995
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 1 3 4 ::: 2999
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3021
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3023
#pragma line 22 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 2 3 4 ::: 3025
#pragma line 58 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3026
#pragma line 88 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3049
#pragma line 124 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3069
#pragma line 211 "/usr/include/x86_64-linux-gnu/bits/pthreadtypes.h" 3 4 ::: 3139
#pragma line 271 "/usr/include/x86_64-linux-gnu/sys/types.h" 2 3 4 ::: 3170
#pragma line 315 "/usr/include/stdlib.h" 2 3 4 ::: 3171
#pragma line 465 "/usr/include/stdlib.h" 3 4 ::: 3314
#pragma line 1 "/usr/include/alloca.h" 1 3 4 ::: 3343
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 3368
#pragma line 56 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 3393
#pragma line 25 "/usr/include/alloca.h" 2 3 4 ::: 3396
#pragma line 493 "/usr/include/stdlib.h" 2 3 4 ::: 3405
#pragma line 514 "/usr/include/stdlib.h" 3 4 ::: 3418
#pragma line 533 "/usr/include/stdlib.h" 3 4 ::: 3425
#pragma line 555 "/usr/include/stdlib.h" 3 4 ::: 3437
#pragma line 575 "/usr/include/stdlib.h" 3 4 ::: 3448
#pragma line 635 "/usr/include/stdlib.h" 3 4 ::: 3495
#pragma line 658 "/usr/include/stdlib.h" 3 4 ::: 3504
#pragma line 713 "/usr/include/stdlib.h" 3 4 ::: 3511
#pragma line 729 "/usr/include/stdlib.h" 3 4 ::: 3517
#pragma line 753 "/usr/include/stdlib.h" 3 4 ::: 3532
#pragma line 912 "/usr/include/stdlib.h" 3 4 ::: 3683
#pragma line 948 "/usr/include/stdlib.h" 3 4 ::: 3685
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdlib-float.h" 1 3 4 ::: 3694
#pragma line 956 "/usr/include/stdlib.h" 2 3 4 ::: 3712
#pragma line 4 "./gemm.h" 2 ::: 3715
#pragma line 1 "./support.h" 1 ::: 3716
#pragma line 1 "/usr/include/inttypes.h" 1 3 4 ::: 3718
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 1 3 4 ::: 3746
#pragma line 1 "/usr/include/stdint.h" 1 3 4 ::: 3780
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wchar.h" 1 3 4 ::: 3807
#pragma line 27 "/usr/include/stdint.h" 2 3 4 ::: 3839
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 3840
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 3842
#pragma line 28 "/usr/include/stdint.h" 2 3 4 ::: 3844
#pragma line 47 "/usr/include/stdint.h" 3 4 ::: 3851
#pragma line 116 "/usr/include/stdint.h" 3 4 ::: 3913
#pragma line 132 "/usr/include/stdint.h" 3 4 ::: 3921
#pragma line 152 "/usr/include/stdint.h" 3 4 ::: 3926
#pragma line 200 "/usr/include/stdint.h" 3 4 ::: 3966
#pragma line 211 "/usr/include/stdint.h" 3 4 ::: 3968
#pragma line 223 "/usr/include/stdint.h" 3 4 ::: 3970
#pragma line 235 "/usr/include/stdint.h" 3 4 ::: 3972
#pragma line 255 "/usr/include/stdint.h" 3 4 ::: 3985
#pragma line 287 "/usr/include/stdint.h" 3 4 ::: 4009
#pragma line 297 "/usr/include/stdint.h" 3 4 ::: 4011
#pragma line 34 "/opt/Xilinx/Vivado_HLS/2017.1/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 2 3 4 ::: 4013
#pragma line 28 "/usr/include/inttypes.h" 2 3 4 ::: 4014
#pragma line 51 "/usr/include/inttypes.h" 3 4 ::: 4022
#pragma line 85 "/usr/include/inttypes.h" 3 4 ::: 4026
#pragma line 101 "/usr/include/inttypes.h" 3 4 ::: 4028
#pragma line 117 "/usr/include/inttypes.h" 3 4 ::: 4030
#pragma line 133 "/usr/include/inttypes.h" 3 4 ::: 4032
#pragma line 150 "/usr/include/inttypes.h" 3 4 ::: 4034
#pragma line 159 "/usr/include/inttypes.h" 3 4 ::: 4036
#pragma line 168 "/usr/include/inttypes.h" 3 4 ::: 4038
#pragma line 186 "/usr/include/inttypes.h" 3 4 ::: 4042
#pragma line 202 "/usr/include/inttypes.h" 3 4 ::: 4044
#pragma line 218 "/usr/include/inttypes.h" 3 4 ::: 4046
#pragma line 234 "/usr/include/inttypes.h" 3 4 ::: 4048
#pragma line 251 "/usr/include/inttypes.h" 3 4 ::: 4050
#pragma line 270 "/usr/include/inttypes.h" 3 4 ::: 4059
#pragma line 289 "/usr/include/inttypes.h" 3 4 ::: 4066
#pragma line 3 "./support.h" 2 ::: 4091
#pragma line 74 "./support.h" ::: 4150
#pragma line 5 "./gemm.h" 2 ::: 4211
#pragma line 2 "gemm.c" 2 ::: 4237
#pragma line 9 "gemm.c" ::: 4247
#pragma line 12 "gemm.c" ::: 4253
#pragma line 14 "gemm.c" ::: 4260
